<a href="https://colab.research.google.com/github/tagtag/TDPCAbasedFE/blob/main/Table5_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
install.packages("rTensor")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)



In [4]:
N<-1000
M<-6
N1<-10
s<-2
set.seed(1)
require(rTensor)
cc <- matrix(0,M,M)
cc[1:(M/2),1:(M/2)] <- 1
#cc[(M/3+1):(2*M/3),(M/3+1):(2*M/3)] <-1
cc1 <- matrix(0,M,M)
cc2 <- matrix(0,M,M)
cc1[1:(M/2),]<-1
cc2[,1:(M/2)]<-1
#cc1[(M/3+1):(2*M/3),]<-1
#cc1[(2*M/3+1):M,]<-2
#cc2[,(M/3+1):(2*M/3)]<-1
#cc2[,(2*M/3+1):M]<-2
t1 <- NULL
t2<- NULL
t3<- NULL
for (i in c(1:100))
{
cat(i,"\n")
x <- array(NA,c(M,M,N))
x[1:(M/2),1:(M/2),1:N1] <- rnorm(N1*(M/2)*(M/2),s)
#x[(M/3+1):(2*M/3),(M/3+1):(2*M/3),1:N1] <- rnorm(N1*(M/3)*(M/3),s)
x[is.na(x)]<- rnorm(sum(is.na(x)))
HOSVD <- hosvd(as.tensor(x),c(min(10,M),min(10,M),10))
P <- pchisq(scale(HOSVD$U[[3]][,1])^2,1,lower.tail=F)
t1 <- cbind(t1,p.adjust(P,"BH")<0.01)
x1<-x
dim(x1)<- c(M*M,N)
LM <- lm(x1~factor(cc))
SLM <- summary(LM)
fs<- t(data.frame(lapply(SLM,"[",10)))
P1 <- pf(fs[,1],fs[,2],fs[,3],lower.tail=F)
t2 <- cbind(t2,p.adjust(P1,"BH")<0.01)
LM1 <- lm(x1~factor(cc1)+factor(cc2))
SLM1 <- summary(LM1)
fs1 <- t(data.frame(lapply(SLM1,"[",10)))
P2 <- pf(fs1[,1],fs1[,2],fs1[,3],lower.tail=F)
t3 <- cbind(t3,p.adjust(P2,"BH")<0.01)
}

Loading required package: rTensor



1 
  |======================================================================| 100%
2 
  |======================================================================| 100%
3 
  |======================================================================| 100%
4 
  |======================================================================| 100%
5 
  |======================================================================| 100%
6 
  |======================================================================| 100%
7 
  |======================================================================| 100%
8 
  |======================================================================| 100%
9 
  |======================================================================| 100%
10 
  |======================================================================| 100%
11 
  |======================================================================| 100%
12 
  |======================================================================| 100%
1

In [8]:
TP <- sum(rowSums(t1)[1:10])/100
FN <- 10-TP
FP <- sum(rowSums(t1)[11:990])/990
TN <- 990-FP
matrix(c(TP,FN,FP,TN),2)

[,1] [,2]        
[1,] 6.39 1.010101e-03
[2,] 3.61 9.899990e+02

In [6]:
TP <- sum(rowSums(t2)[1:10])/100
 FN <- 10-TP
 FP <- sum(rowSums(t2)[11:990])/990
TN <- 990-FP
matrix(c(TP,FN,FP,TN),2)

[,1]        [,2]   
[1,] 7.400000000   2.600
[2,] 0.001010101 989.999

In [9]:
TP <- sum(rowSums(t3)[1:10])/100
FN <- 10-TP
FP <- sum(rowSums(t3)[11:990])/990
TN <- 990-FP
matrix(c(TP,FN,FP,TN),2)

[,1] [,2]        
[1,] 0.62 4.040404e-03
[2,] 9.38 9.899960e+02